apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mock-mlops.fullname" . }}
  labels:
    {{- include "mock-mlops.labels" . | nindent 4 }}
type: Opaque
data:
  portainerPassword: {{ .Values.portainer.vars.password | b64enc }}
  mysqlPassword: {{ .Values.mysql.vars.password | b64enc }}
  clientID: {{ .Values.keycloak.vars.clientID | b64enc }}
  clientSecret: {{ .Values.keycloak.vars.clientSecret | b64enc }}
