apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mock-mlops.fullname" . }}
  labels:
    {{- include "mock-mlops.labels" . | nindent 4 }}
type: Opaque
data:
  portainerPassword: {{ .Values.secrets.portainerPassword | b64enc }}
