{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-mlops.fullname" . }}-portainer-agent
  labels:
    {{- include "mock-mlops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "mock-mlops.fullname" . }}-portainer-agent
  ports:
    - port: {{ .Values.agent.port }}
      targetPort: {{ .Values.agent.port }}
      protocol: TCP
      name: http
{{- end }}
