{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mock-mlops.fullname" . }}-portainer-agent
  labels:
    {{- include "mock-mlops.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
