apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-mlops.fullname" . }}-portainer
  labels:
    {{- include "mock-mlops.portainer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portainer.service.type }}
  ports:
    - port: {{ .Values.portainer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mock-mlops.portainer.labels" . | nindent 4 }}
