---
apiVersion: batch/v1
kind: Job
metadata:
  name: traning
  namespace: trainings
spec:
  template:
    spec:
      containers:
        - name: traning
          image: localhost:5001/mock-mlops-application-training:main
      restartPolicy: Never
  backoffLimit: 4
