---
name: build

on:
  pull_request:
    branches:
      - v*.*.*
      - latest
    tags:
      - v*.*.*
      - latest
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    name: build training
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: training/Dockerfile
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta-training
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-training
      - uses: docker/build-push-action@v3
        with:
          context: training
          push: true
          tags: |
            ${{ steps.meta-training.outputs.tags }}
          labels: ${{ steps.meta-training.outputs.labels }}
          file: training/Dockerfile
      - id: meta-extra-services
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-extra-services
      - uses: docker/build-push-action@v3
        with:
          context: service
          push: true
          tags: |
            ${{ steps.meta-extra-services.outputs.tags }}
          labels: ${{ steps.meta-extra-services.outputs.labels }}
          file: service/Dockerfile
